version: "3.8"

services:
  jupyeter:
    container_name: jupyter01
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
      NB_UID: 1000
      NB_GID: 100
      GRANT_SUDO: "yes"
      PYTHONUNBUFFERED: 1
    ports:
      - 8888:8888
    restart: "no"
    volumes:
      - type: bind
        source: ./data
        target: /home/jovyan/work
